use Mix.Config

if File.exists?("config/ebay_creds.exs") do
  import_config "ebay_creds.exs"
end

if File.exists?("config/big_commerce_creds.exs") do
  import_config "big_commerce_creds.exs"
end

# Configure your database
config :sell_set_go_api, SellSetGoApi.Repo,
  username: "dzine-hub",
  password: "dzinehub@123",
  database: "sell_set_go_api_dev",
  hostname: "storage",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :sell_set_go_api, SellSetGoApiWeb.Endpoint,
  http: [port: 4001],
  https: [
    port: 4000,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

config :oauth2, debug: true

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console,
  metadata: [:pid, :request_id],
  format: "$time $metadata[$level] $message\n"

config :ex_aws,
  s3: [
    host: System.get_env("AWS_HOST", "s3"),
    scheme: System.get_env("AWS_SCHEME", "http://"),
    port: String.to_integer(System.get_env("AWS_PORT", "9000")),
    region: {:system, "AWS_REGION"}
  ],
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]

config :sell_set_go_api, :environment, :dev
# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
